[tool.isort]
skip = "monkey/monkey_island/cc/ui"
known_first_party = "common,infection_monkey,monkey_island"
line_length = 100
### for compatibility with black
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
